/*
Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then 
add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    
  //will return {Array} of amount of letters 'map' of given {string} 's' at its array position
  var getAlphabetAmount = function(s){
    var map = Array.apply(null, Array(26)).map(Number.prototype.valueOf,0);;
    var pos = 0;
    
    for (var i=0; i<s.length; i++){
        pos = s[i].charCodeAt() - 97;
        if (map[pos] === undefined){
            map[pos] = 1;
        } else {
            map[pos]++;
        }
    }
    
    return map;
  };
    
  var sMap = getAlphabetAmount(s);
  var tMap = getAlphabetAmount(t);
  var FIRST_POS = 97;
  
  //comparing two maps
  for (var i=0; i<26; i++){
    if (sMap[i] !== tMap[i]){
      return String.fromCharCode(FIRST_POS + i);
    }
  }
  
};
